### ISSUE TITLE
URL API for linking/embedding?

### ISSUE THREAD

**Issue by NinjaCowboy** [shikoshib/winerr#3]
It would be nice to be able to request a specific error message through URL parameters so that generated errors could be linked to or embedded into `<img>` tags.

**Comment by NinjaCowboy** [comment]
Actually, it appears that the image is generated client-side, so this wouldn't be possible.

**Comment by shikoshib** [comment]
Hello! There is an actual working API, but right now it only activates if you use Firefox (because it has a very obscure bug where some assets are not placed).
I'll make a documentation on it one day.
Thanks for suggestion!
